### ISSUE TITLE
[Bug]: blender slow and irresponsive 

### ISSUE THREAD

**Issue by seisdr** [termux-user-repository/tur#1422]
### Problem description

Launching blender from command line it takes a longer time to fully start longer than when running with chroot and then after it start it response very slow 
```
blender/tur-packages,now 1:3.6.16-1 aarch64 [installed]
```

### What steps will reproduce the bug?

.

### What is the expected behavior?

.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=1877
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.danyael.xyz/termux/termux-main stable main
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
# root-repo (sources.list.d/root.list)
deb https://termux.danyael.xyz/termux/termux-root root stable
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous tur-hacking
# x11-repo (sources.list.d/x11.list)
deb https://termux.danyael.xyz/termux/termux-x11 x11 main
Updatable packages:
containerd/root 1.6.21-4 aarch64 [upgradable from: 1.6.21-1]
vim/stable 9.1.0950 aarch64 [upgradable from: 9.1.0800]
xfce4-terminal/x11 1.1.4 aarch64 [upgradable from: 1.1.3]
termux-tools version:
1.44.6
Android version:
14
Kernel build information:
Linux localhost 4.19.321-Spiral-g1ec85879556b-dirty #21 SMP PREEMPT Sun Nov 3 03:06:52 UTC 2024 aarch64 Android
Device manufacturer:
realme
Device model:
RMX3370
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:15
com.termux.styling versionCode:1000
com.termux.api versionCode:51

```

**Comment by IntinteDAO** [comment]
Please give info about OpenGL configuration

glxinfo | grep OpenGL

**Comment by licy183** [comment]
This is intended if you're using llvmpipe, so this is not a bug

**Comment by seisdr** [comment]
Yes sorry it's llvmpipe but i have mesa-zink package installed so i thought it was using zink , anyway with `grun -s` blender  doesn't work and crash
```
~ $ MESA_LOADER_DRIVER_OVERRIDE=zink glxheads
glxheads: exercise multiple GLX connections (any key = exit)
Usage:
  glxheads xdisplayname ...
Example:
  glxheads :0 mars:0 venus:1
Name: :0
  Display:     0xb400f765cab16380
  Window:      0x1c00002
  Context:     0xb400f7646ab104d0
  GL_VERSION:  4.5 (Compatibility Profile) Mesa 22.0.5
  GL_VENDOR:   Mesa/X.org
  GL_RENDERER: llvmpipe (LLVM 11.1.0, 128 bits)
^C
~ $ grun -s MESA_LOADER_DRIVER_OVERRIDE=zink glxheads
glxheads: exercise multiple GLX connections (any key = exit)
Usage:
  glxheads xdisplayname ...
Example:
  glxheads :0 mars:0 venus:1
Name: :0
  Display:     0xb31bc63821e0
  Window:      0x1c00002
  Context:     0xb31bc64156f0
  GL_VERSION:  4.6 (Compatibility Profile) Mesa 24.2.6.termux-glibc-0
  GL_VENDOR:   Mesa
  GL_RENDERER: zink Vulkan 1.3(Turnip Adreno (TM) 650 (MESA_TURNIP))
^C
~ $ grun -s MESA_LOADER_DRIVER_OVERRIDE=zink blender
Read prefs: "/data/data/com.termux/files/home/.config/blender/3.6/config/userpref.blend"
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/modules/bpy/utils/__init__.py", line 129, in _test_import
    mod = __import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/startup/bl_operators/__init__.py", line 45, in <module>
    __import__(name=__name__, fromlist=_modules)
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/startup/bl_operators/uvcalc_transform.py", line 3, in <module>
    import math
ModuleNotFoundError: No module named 'math'
Exception in module register(): /data/data/com.termux/files/usr/share/blender/3.6/scripts/addons/cycles/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/addons/cycles/__init__.py", line 128, in register
    from . import properties
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/addons/cycles/properties.py", line 17, in <module>
    from math import pi
ModuleNotFoundError: No module named 'math'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/addons/pose_library/__init__.py", line 22, in <module>
    from . import gui, keymaps, operators, conversion
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/addons/pose_library/operators.py", line 7, in <module>
    from pathlib import Path
  File "/data/data/com.termux/files/usr/glibc/lib/python3.12/pathlib.py", line 20, in <module>
    from urllib.parse import quote_from_bytes as urlquote_from_bytes
  File "/data/data/com.termux/files/usr/glibc/lib/python3.12/urllib/parse.py", line 36, in <module>
    import math
ModuleNotFoundError: No module named 'math'
Error: dropbox with unknown operator: WM_OT_drop_blend_file
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/modules/bpy/utils/__init__.py", line 676, in keyconfig_set
    execfile(filepath)
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/modules/bpy/utils/__init__.py", line 104, in execfile
    mod_spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/presets/keyconfig/Blender.py", line 323, in <module>
    blender_default = bpy.utils.execfile(os.path.join(DIRNAME, "keymap_data", "blender_default.py"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/modules/bpy/utils/__init__.py", line 104, in execfile
    mod_spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/share/blender/3.6/scripts/presets/keyconfig/keymap_data/blender_default.py", line 228, in <module>
    from math import pi
ModuleNotFoundError: No module named 'math'

WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Curve Edit Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Edit Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Draw brush)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Erase)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Fill)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Tint)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Draw)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Blur)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Average)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Smear)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Replace)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Smooth)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Thickness)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Strength)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Grab)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Push)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Twist)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Pinch)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Randomize)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt (Clone)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Weight Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Weight (Draw)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Weight (Blur)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Weight (Average)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Weight (Smear)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Paint Face Mask (Weight, Vertex, Texture)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Paint Vertex Selection (Weight, Vertex)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Paint Curve'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Weight Paint'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Vertex Paint'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Pose'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Object Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Curve'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Curves'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Image Paint'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Sculpt'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Mesh'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Armature'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Metaball'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Lattice'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Particle'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Sculpt Curves'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Font'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Object Non-modal'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Frames'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap '3D View Generic'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap '3D View'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Window'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Screen'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Curve Edit Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Edit Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Draw brush)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Erase)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Fill)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Paint (Tint)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Sculpt Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex Mode'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Draw)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Blur)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Average)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Smear)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_keymap.c:455 WM_keymap_poll: empty keymap 'Grease Pencil Stroke Vertex (Replace)'
WARN (wm.keymap): source/blender/windowmanager/intern/wm_ke
```

**Comment by licy183** [comment]
`blender` in TUR is linked against bionic libc rather than glibc, so it will not work with grun.

**Comment by seisdr** [comment]
Okay I'll close this since I'm using blender in a chroot but where's zink in termux? I tried all mesa packages available none showed zink
