### ISSUE TITLE
[package request]: Add python-cryptography

### ISSUE THREAD

**Issue by T-Dynamos** [termux-user-repository/tur#25]
Needs rust compiler

And can we add issue templates?

**Comment by kcubeterm** [comment]
Yeah. We can add issue template. Will add it. Or Go ahead if you can do it in more better ways

**Comment by T-Dynamos** [comment]
I tried building but ...
```
Traceback (most recent call last):
  File "/home/builder/.termux-build/python-cryptography/src/setup.py", line 14, in <module>
    from setuptools_rust import RustExtension
  File "/home/builder/.termux-build/python-cryptography/build/python-crossenv-prefix/build/lib/python3.10/site-packages/setuptools_rust/__init__.py", line 1, in <module>
    from .build import build_rust
  File "/home/builder/.termux-build/python-cryptography/build/python-crossenv-prefix/build/lib/python3.10/site-packages/setuptools_rust/build.py", line 17, in <module>
    from distutils.sysconfig import get_config_var
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/builder/.termux-build/python-cryptography/build/python-crossenv-prefix/lib/site.py", line 74, in exec_module
    _patch_module(module, self.patch)
  File "/home/builder/.termux-build/python-cryptography/build/python-crossenv-prefix/lib/site.py", line 55, in _patch_module
    exec(src, module.__dict__, module.__dict__)
  File "<string>", line 13, in <module>
NameError: name '_init_posix' is not defined
```
[build.sh](https://github.com/T-Dynamos/tur/blob/master/tur/python-cryptography/build.sh)

**Comment by kcubeterm** [comment]
You need to install cffi for host as well. Put one another line just after build-pip line. With ` pip install cffi `

**Comment by kcubeterm** [comment]
And let's open pull request as well. PR need not be submitted only if you successfully build packages locally. No problems if its fails or we could't make it compile. We just close it. Simple!!

**Comment by T-Dynamos** [comment]
> You need to install cffi for host as well. Put one another line just after build-pip line. With `pip install cffi` . It's always nice idea to install those packages from build-pip as well which you install with pip and vice-versa

Thanks ! 
I will do it from now
