### ISSUE TITLE
[Bug]: electron21 not building

### ISSUE THREAD

**Issue by johndebia2022** [termux-user-repository/tur#357]
### Problem description

[1394/76140] STAMP obj/electron/shell/common/extensions/api/generated_api_json_strings_bundle_generator_schema.stamp
2023-04-12T02:39:08.5408965Z [1395/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/RendererGLX.o
2023-04-12T02:39:09.6524547Z [1396/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/DmaBufImageSiblingEGL.o
2023-04-12T02:39:09.8416594Z [1397/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/glx_utils.o
2023-04-12T02:39:12.5086383Z [1398/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/ContextEGL.o
2023-04-12T02:39:13.5435922Z [1399/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/DisplayEGL.o
2023-04-12T02:39:14.3321430Z [1400/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/FunctionsEGLDL.o
2023-04-12T02:39:15.1275894Z [1401/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/ImageGL.o
2023-04-12T02:39:16.1772295Z [1402/76140] ACTION //electron:electron_isolated_renderer_bundle(//build/toolchain/linux/unbundle:default)
2023-04-12T02:39:16.1776554Z FAILED: gen/electron/js2c/isolated_bundle.js 
2023-04-12T02:39:16.1781673Z python3 ../../../cache/tmp-checkout/src/electron/build/npm-run.py --silent webpack -- --config /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/build/webpack/webpack.config.isolated_renderer.js --output-filename=isolated_bundle.js --output-path=/home/builder/.termux-build/electron21/build/out/Release/gen/electron/js2c --env.buildflags=/home/builder/.termux-build/electron21/build/out/Release/gen/electron/buildflags/buildflags.h --env.mode=production
2023-04-12T02:39:16.1789059Z NPM script 'webpack' failed with code '1':
2023-04-12T02:39:16.1789606Z /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:133
2023-04-12T02:39:16.1789992Z 		if(isError) throw e;
2023-04-12T02:39:16.1790199Z 		            ^
2023-04-12T02:39:16.1790323Z 
2023-04-12T02:39:16.1790492Z Error: error:0308010C:digital envelope routines::unsupported
2023-04-12T02:39:16.1790801Z     at new Hash (node:internal/crypto/hash:71:19)
2023-04-12T02:39:16.1791090Z     at Object.createHash (node:crypto:133:10)
2023-04-12T02:39:16.1791672Z     at module.exports (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/webpack/lib/util/createHash.js:135:53)
2023-04-12T02:39:16.1792375Z     at NormalModule._initBuildHash (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/webpack/lib/NormalModule.js:417:16)
2023-04-12T02:39:16.1793084Z     at handleParseError (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/webpack/lib/NormalModule.js:471:10)
2023-04-12T02:39:16.1793749Z     at /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/webpack/lib/NormalModule.js:503:5
2023-04-12T02:39:16.1794370Z     at /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/webpack/lib/NormalModule.js:358:12
2023-04-12T02:39:16.1794989Z     at /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:373:3
2023-04-12T02:39:16.1795684Z     at iterateNormalLoaders (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
2023-04-12T02:39:16.1796415Z     at iterateNormalLoaders (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
2023-04-12T02:39:16.1797077Z     at /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:236:3
2023-04-12T02:39:16.1798345Z     at context.callback (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
2023-04-12T02:39:16.1799048Z     at makeSourceMapAndFinish (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/ts-loader/dist/index.js:59:5)
2023-04-12T02:39:16.1799720Z     at successLoader (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/ts-loader/dist/index.js:41:5)
2023-04-12T02:39:16.1800366Z     at Object.loader (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/ts-loader/dist/index.js:24:5)
2023-04-12T02:39:16.1801036Z     at LOADER_EXECUTION (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
2023-04-12T02:39:16.1801734Z     at runSyncOrAsync (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
2023-04-12T02:39:16.1802601Z     at iterateNormalLoaders (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
2023-04-12T02:39:16.1803378Z     at Array.<anonymous> (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
2023-04-12T02:39:16.1805110Z     at Storage.finished (/home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
2023-04-12T02:39:16.1805840Z     at /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
2023-04-12T02:39:16.1806483Z     at /home/builder/.termux-build/electron21/cache/tmp-checkout/src/electron/node_modules/graceful-fs/graceful-fs.js:90:16
2023-04-12T02:39:16.1806961Z     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
2023-04-12T02:39:16.1807600Z   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
2023-04-12T02:39:16.1807991Z   library: 'digital envelope routines',
2023-04-12T02:39:16.1808281Z   reason: 'unsupported',
2023-04-12T02:39:16.1808573Z   code: 'ERR_OSSL_EVP_UNSUPPORTED'
2023-04-12T02:39:16.1808779Z }
2023-04-12T02:39:16.1808886Z 
2023-04-12T02:39:16.1808972Z Node.js v18.15.0
2023-04-12T02:39:16.1809099Z 
2023-04-12T02:39:16.5297953Z [1403/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/ProgramPipelineGL.o
2023-04-12T02:39:18.3404798Z [1404/76140] CXX obj/third_party/angle/src/libANGLE/renderer/gl/angle_gl_backend/ProgramGL.o
2023-04-12T02:39:18.3405380Z ninja: build stopped: subcommand failed.
2023-04-12T02:39:18.3689582Z cp: cannot stat 'out/Release/electron': No such file or directory
2023-04-12T02:39:18.3690183Z cp: cannot stat 'out/Release/chrome_crashpad_handler': No such file or directory
2023-04-12T02:39:18.3690756Z cp: cannot stat 'out/Release/chrome_100_percent.pak': No such file or directory
2023-04-12T02:39:18.3691282Z cp: cannot stat 'out/Release/chrome_200_percent.pak': No such file or directory
2023-04-12T02:39:18.3691769Z cp: cannot stat 'out/Release/resources.pak': No such file or directory
2023-04-12T02:39:18.3692263Z cp: cannot stat 'out/Release/snapshot_blob.bin': No such file or directory
2023-04-12T02:39:18.3692781Z cp: cannot stat 'out/Release/v8_context_snapshot.bin': No such file or directory
2023-04-12T02:39:18.3693260Z cp: cannot stat 'out/Release/icudtl.dat': No such file or directory
2023-04-12T02:39:18.3693728Z cp: cannot stat 'out/Release/libEGL.so': No such file or directory
2023-04-12T02:39:18.3694202Z cp: cannot stat 'out/Release/libGLESv2.so': No such file or directory
2023-04-12T02:39:18.3694673Z cp: cannot stat 'out/Release/libvulkan.so.1': No such file or directory
2023-04-12T02:39:18.3695175Z cp: cannot stat 'out/Release/libvk_swiftshader.so': No such file or directory
2023-04-12T02:39:18.3696027Z cp: cannot stat 'out/Release/vk_swiftshader_icd.json': No such file or directory
2023-04-12T02:39:18.3696527Z cp: cannot stat 'out/Release/libffmpeg.so': No such file or directory
2023-04-12T02:39:18.5554873Z ==> Build failed with 1
2023-04-12T02:39:18.5623901Z ##[error]Process completed with exit code 1.
2023-04-12T02:39:18.5749719Z Post job cleanup.
2023-04-12T02:39:18.9101148Z [command]/usr/bin/git version
2023-04-12T02:39:18.9327272Z git version 2.40.0
2023-04-12T02:39:18.9391968Z Temporarily overriding HOME='/home/runner/work/_temp/e4df735d-c169-45d2-abaf-06e3c0b3b5e2' before making global git config changes

[3.txt](https://github.com/termux-user-repository/tur/files/11206611/3.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by licy183** [comment]
I may be unable to fix it until August. I've started school and the network in my school is billed according to the traffic. Getting source code of electron costs about 60GB and I don't want to pay for it anyway.

**Comment by licy183** [comment]
https://github.com/termux-user-repository/electron-tur-builder/commit/e86d0b382b16541dd02010338b93b4dc0c62c492
