### ISSUE TITLE
How to setup current Python version on build.

### ISSUE THREAD

**Issue by IntinteDAO** [termux-user-repository/tur#524]
So, I want to port Pitivi software on Termux. This package required Python.h header file, but it's not available on Termux Build System by default. I can get it from Termux as dependency, but the default version of Python in Build System is 3.10, but in repository it's 3.11 and the software doesn't work propertly.

Is it possible to force using Python 3.11 (or just the same as in Termux repo)? Or I am just too stupid? ;)

**Comment by licy183** [comment]
You need to set `TERMUX_PKG_SETUP_PYTHON=true`.

**Comment by IntinteDAO** [comment]
Partially works. I think there is a bug in libxml2-python. Can you check it? (in the free time ofc)

192.109.244.21/pitivi.tar.gz

In short libxml2-python cannot be imported by script, because:

```
Traceback (most recent call last):
  File "/usr/bin/itstool", line 27, in <module>
    import libxml2
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/libxml2.py", line 1, in <module>
    import libxml2mod
ImportError: /data/data/com.termux/files/usr/lib/python3.11/site-packages/libxml2mod.so: cannot open shared object file: No such file or directory
```

But the file is here, so not sure why it returns this error

**Comment by T-Dynamos** [comment]
You running it in proot? 

> ```
>   File "/usr/bin/itstool", line 27, in <module>
> ```

**Comment by IntinteDAO** [comment]
No, in TUR build docker script

But I think the app or gst-plugins-bad is broken, because Pitivi can't load GstTranscoder, but I don't see any issues in strace :/
