### ISSUE TITLE
Trying to build ChemicalFun

### ISSUE THREAD

**Issue by defencedog** [termux-user-repository/tur#70]
Bcz I am using `scipy` I have installed it from its-pointless repo whereas `python3.9` from tur repo. In effect now I have x2 pythons.

I am building [ChemicalFun](https://bitbucket.org/gems4/chemicalfun/src/master/) 
These were some dependencies `pkg install libspdlog fmt` & `python3.9 -m pip install pybind11[global]`

```
git clone https://github.com/thermohub/thermofun.git && cd thermofun 
mkdir build 
cd build 
cmake .. 

```
Output

```
-- The CXX compiler identification is Clang 14.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /data/data/com.termux/files/usr/bin/python3 (found suitable version "3.10.6", minimum required is "3.6")
-- Found PythonLibs: /data/data/com.termux/files/usr/lib/libpython3.10.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Found pybind11: /data/data/com.termux/files/usr/include (found version "2.10.0")
-- Found pybind11 v2.10.0: /data/data/com.termux/files/usr/include;/data/data/com.termux/files/usr/include/python3.10
-- Found pybind11 v2.10.0: /data/data/com.termux/files/usr/include;/data/data/com.termux/files/usr/include/python3.10
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found spdlog v1.10.0
-- Configuring done
-- Generating done
-- Build files have been written to: /data/data/com.termux/files/home/chemicalfun/build
```
The problem is that it keep detecting `python3.10` & I want to access it in `python3.9` where my jupyter & all stack is installed
I have tried these before `cmake .. ` but failed
```
export PYTHONPATH=$PYTHONPATH:/data/data/com.termux/files/usr/lib/python3.9/site-packages
export PythonInterp=$PythonInterp:/data/data/com.termux/files/usr/bin/python3.9
export PythonLibs=$PythonLibs:/data/data/com.termux/files/usr/lib/libpython3.9.so

```

**Comment by T-Dynamos** [comment]
Just remove python3.10

or try this 
```
rm -rf $PREFIX/bin/python3 
ln -s $PREFIX/bin/python3.9 $PREFIX/bin/python3
```

**Comment by defencedog** [comment]
@T-Dynamos 
I have done using this, perhaps more [official](https://pybind11.readthedocs.io/en/stable/faq.html)  way!

`cmake .. -DPYTHON_EXECUTABLE=/data/data/com.termux/files/usr/bin/python3.9 -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr`

I have successfully build & installed `chemicalfun` but there is a weird issue
The final output
```
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunTargets.cmake
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunTargets-relwithdebinfo.cmake
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunConfig.cmake
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunConfigVersion.cmake
-- Installing: /data/data/com.termux/files/usr/lib/[libChemicalFun.so](http://libchemicalfun.so/)
-- Set runtime path of "/data/data/com.termux/files/usr/lib/[libChemicalFun.so](http://libchemicalfun.so/)" to ""
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/ChemicalData.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/ChemicalFormulaParser.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/MoietyParser.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/ChemicalReactions.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Combiner.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Generator.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/MatrixUtils.h
-- Installing: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Reaction.h
running install
running build
running build_py
running install_lib
creating /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun
copying build/lib/chemicalfun/__init__.py -> /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun
copying build/lib/chemicalfun/[PyChemicalFun.cpython-39.so](http://pychemicalfun.cpython-39.so/) -> /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun
byte-compiling /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun/__init__.py to __init__.cpython-39.pyc
running install_egg_info
Writing /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun-0.1.4-py3.9.egg-info
```
`install_manifest` file contents
```
GNU nano 6.3                           install_manifest.txt
/data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunTargets.cmake
/data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunTargets-relwithdebinfo.cmake
/data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunConfig.cmake
/data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunConfigVersion.cmake
/data/data/com.termux/files/usr/lib/libChemicalFun.so
/data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser.h
/data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/ChemicalData.h
/data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/ChemicalFormulaParser.h
/data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/MoietyParser.h
/data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator.h
/data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/ChemicalReactions.h
/data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Combiner.h
/data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Generator.h
/data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/MatrixUtils.h
/data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Reaction.h
```
But i cannot find  file `libChemicalFun.so` ...all other files are there where they are supposed to be. Any help. I therefore cannot use this package in python

**Comment by T-Dynamos** [comment]
```
-- Installing: /data/data/com.termux/files/usr/lib/[libChemicalFun.so](http://libchemicalfun.so/)
-- Set runtime path of "/data/data/com.termux/files/usr/lib/[libChemicalFun.so](http://libchemicalfun.so/)" to ""
```
This is weird (not a correct file name)
Can you send output of `ls $PREFIX/lib/ | grep "Chemical"`?

**Comment by defencedog** [comment]
I am a chemical engineer ...just a superuser! So plz bear with me. 
```
~ $ ls $PREFIX/lib/ | grep "Chemical"
libChemicalFun.so
```
Am sorry to bother but perhaps I need bigger glasses. Problem solved. The capital C creates problem in alphabetically arranging filenames

**Comment by defencedog** [comment]
@T-Dynamos can you shed some light on this error as well
```
~ $ python -c "import chemicalfun; print(chemicalfun.__version__)"                                 Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun/__init__.py", line 1, in <module>
    from chemicalfun.PyChemicalFun import *
ImportError: dlopen failed: cannot locate symbol "_Py_FalseStruct" referenced by "/data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun/PyChemicalFun.cpython-39.so"...
```

**Comment by licy183** [comment]
`export LDFLAGS="-Wl,--no-as-needed,-lpython3.9"` before  `cmake .. -DXXX`

**Comment by T-Dynamos** [comment]
@licy183 lets package it

**Comment by defencedog** [comment]
@licy183 @T-Dynamos 
Thanks beforehand ...somethings that I had done, may help you
`pkg install libspdlog eigen `

Latest `fmt` gave error so I have to compile v8.1.1
```
unzip fmt-8.1.1.zip
cd fmt-8.1.1
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr/local
```
Success
```
Install the project...
-- Install configuration: "Release"
-- Installing: /data/data/com.termux/files/usr/local/lib/libfmt.a
-- Installing: /data/data/com.termux/files/usr/local/lib/cmake/fmt/fmt-config.cmake
-- Installing: /data/data/com.termux/files/usr/local/lib/cmake/fmt/fmt-config-version.cmake
-- Installing: /data/data/com.termux/files/usr/local/lib/cmake/fmt/fmt-targets.cmake
-- Installing: /data/data/com.termux/files/usr/local/lib/cmake/fmt/fmt-targets-release.cmake
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/args.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/chrono.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/color.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/compile.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/core.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/format.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/format-inl.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/locale.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/os.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/ostream.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/printf.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/ranges.h
-- Installing: /data/data/com.termux/files/usr/local/include/fmt/xchar.h
-- Installing: /data/data/com.termux/files/usr/local/lib/pkgconfig/fmt.pc
```
Todo after install symlinking ...maybe you can find another neat method

```
cd /data/data/com.termux/files/usr/lib
ln -s /data/data/com.termux/files/usr/local/lib/libfmt.a libfmt.a
cd cmake
ln -s  /data/data/com.termux/files/usr/local/lib/cmake/fmt fmt
cd ..
cd pkgconfig
ln -s /data/data/com.termux/files/usr/local/lib/pkgconfig/fmt.pc fmt.pc
cd /data/data/com.termux/files/usr/include
ln -s /data/data/com.termux/files/usr/local/include/fmt fmt
```
There was [similar](https://github.com/opencv/opencv/issues/14868) error in some .h file while cmaking `chemicalfun`, so i did this (forgot .h file location) but it will show up
```
nano eigen.h
   #include <eigen3/Eigen/Core>
   #include <eigen3/Eigen/SparseCore>
```

**Comment by defencedog** [comment]
> `export LDFLAGS="-Wl,--no-as-needed,-lpython3.9"` before `cmake .. -DXXX`

`export LDFLAGS="-Wl,--no-as-needed,-lpython3.9" && cmake .. -DPYTHON_EXECUTABLE=/data/data/com.termux/files/usr/bin/python3.9 -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr && make -j8 && make install`

Success
```
Consolidate compiler generated dependencies of target ChemicalFun
[ 86%] Built target ChemicalFun
Consolidate compiler generated dependencies of target PyChemicalFun
[100%] Built target PyChemicalFun
[100%] Built target chemicalfun
Install the project...
-- Install configuration: "RelWithDebInfo"
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunTargets.cmake
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunTargets-relwithdebinfo.cmake
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunConfig.cmake
-- Installing: /data/data/com.termux/files/usr/lib/cmake/ChemicalFun/ChemicalFunConfigVersion.cmake
-- Installing: /data/data/com.termux/files/usr/lib/libChemicalFun.so
-- Set runtime path of "/data/data/com.termux/files/usr/lib/libChemicalFun.so" to ""
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/ChemicalData.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/ChemicalFormulaParser.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/FormulaParser/MoietyParser.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/ChemicalReactions.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Combiner.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Generator.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/MatrixUtils.h
-- Up-to-date: /data/data/com.termux/files/usr/include/ChemicalFun/ReactionsGenerator/Reaction.h
running install
running build
running build_py
running install_lib
copying build/lib/chemicalfun/PyChemicalFun.cpython-39.so -> /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun
running install_egg_info
Removing /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun-0.1.4-py3.9.egg-info
Writing /data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun-0.1.4-py3.9.egg-info
```

A slightly different error
```
python -c "import chemicalfun; print(chemicalfun.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/chemicalfun/__init__.py", line 1, in <module>
    from chemicalfun.PyChemicalFun import *
ImportError: dlopen failed: cannot locate symbol "_ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt2v817basic_string_viewIcEENS_5level10level_enumES6_" referenced by "/data/data/com.termux/files/usr/lib/libChemicalFun.so"...
```

**Comment by T-Dynamos** [comment]
https://github.com/gabime/spdlog/issues/2264

I am on here
```
[  6%] Building CXX object src/CMakeFiles/ChemicalFun.dir/ReactionsGenerator/CanonicalizerLeal16.cpp.o
In file included from /data/data/com.termux/files/home/master/src/ReactionsGenerator/CanonicalizerLeal16.cpp:20:
In file included from /data/data/com.termux/files/home/master/src/Common/Exception.h:26:
In file included from /data/data/com.termux/files/usr/include/spdlog/spdlog.h:12:
In file included from /data/data/com.termux/files/usr/include/spdlog/common.h:45:
In file included from /data/data/com.termux/files/usr/include/spdlog/fmt/fmt.h:27:
/data/data/com.termux/files/usr/include/fmt/core.h:1756:3: error: static_assert failed due to requirement 'formattable' "Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt"
  static_assert(
  ^
/data/data/com.termux/files/usr/include/fmt/core.h:1777:10: note: in instantiation of function template specialization 'fmt::detail::make_value<fmt::basic_format_context<fmt::appender, char>, Eigen::Matrix<double, -1, -1, 0> &>' requested here
  return make_value<Context>(val);
         ^
/data/data/com.termux/files/usr/include/fmt/core.h:1899:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::detail::type::custom_type, Eigen::Matrix<double, -1, -1, 0> &, 0>' requested here
        data_{detail::make_arg<
                      ^
/data/data/com.termux/files/usr/include/fmt/core.h:1918:10: note: in instantiation of function template specialization 'fmt::format_arg_store<fmt::basic_format_context<fmt::appender, char>, Eigen::Matrix<double, -1, -1, 0>>::format_arg_store<Eigen::Matrix<double, -1, -1, 0> &>' requested here
  return {FMT_FORWARD(args)...};
         ^
/data/data/com.termux/files/usr/include/spdlog/logger.h:370:52: note: in instantiation of function template specialization 'fmt::make_format_args<fmt::basic_format_context<fmt::appender, char>, Eigen::Matrix<double, -1, -1, 0> &>' requested here
            fmt::detail::vformat_to(buf, fmt, fmt::make_format_args(std::forward<Args>(args)...));
                                                   ^
/data/data/com.termux/files/usr/include/spdlog/logger.h:90:9: note: in instantiation of function template specialization 'spdlog::logger::log_<Eigen::Matrix<double, -1, -1, 0> &>' requested here
        log_(loc, lvl, fmt, std::forward<Args>(args)...);
        ^
/data/data/com.termux/files/usr/include/spdlog/logger.h:96:9: note: in instantiation of function template specialization 'spdlog::logger::log<Eigen::Matrix<double, -1, -1, 0> &>' requested here
        log(source_loc{}, lvl, fmt, std::forward<Args>(args)...);
        ^
/data/data/com.termux/files/usr/include/spdlog/logger.h:152:9: note: in instantiation of function template specialization 'spdlog::logger::log<Eigen::Matrix<double, -1, -1, 0> &>' requested here
        log(level::debug, fmt, std::forward<Args>(args)...);
        ^
/data/data/com.termux/files/home/master/src/ReactionsGenerator/CanonicalizerLeal16.cpp:99:36: note: in instantiation of function template specialization 'spdlog::logger::debug<Eigen::Matrix<double, -1, -1, 0> &>' requested here
        ChemicalFun::chfun_logger->debug("leal16 \n {} ", R);
                                   ^
1 error generated.
make[2]: *** [src/CMakeFiles/ChemicalFun.dir/build.make:132: src/CMakeFiles/ChemicalFun.dir/ReactionsGenerator/CanonicalizerLeal16.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:149: src/CMakeFiles/ChemicalFun.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by defencedog** [comment]
@T-Dynamos as discussed earlier compile old `fmt-8.1.1` ...termux repo has version 9

**Comment by defencedog** [comment]
@T-Dynamos any help?

**Comment by gdmiron** [comment]
@defencedog  @T-Dynamos I think this is something related to fmt conflict between external library and the version bundled with spdlog. Try compiling all using spdlog 1.10.0 with no external fmt installed. This is how the conda-forge package of chemicalfun is built [recipe-yaml](https://github.com/conda-forge/chemicalfun-feedstock/blob/main/recipe/meta.yaml ).

**Comment by gdmiron** [comment]
https://github.com/conda-forge/spdlog-feedstock/issues/49

**Comment by defencedog** [comment]
@gdmiron `fmt` removed  but 

```
-- The CXX compiler identification is Clang 14.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /data/data/com.termux/files/usr/bin/python3.9 (found suitable version "3.9.13", minimum required is "3.6")
-- Found PythonLibs: /data/data/com.termux/files/usr/lib/libpython3.9.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Found pybind11: /data/data/com.termux/files/usr/include (found version "2.10.0")
-- Found pybind11 v2.10.0: /data/data/com.termux/files/usr/include;/data/data/com.termux/files/usr/include/python3.9
-- Found pybind11 v2.10.0: /data/data/com.termux/files/usr/include;/data/data/com.termux/files/usr/include/python3.9
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
CMake Error at /data/data/com.termux/files/usr/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /data/data/com.termux/files/usr/lib/cmake/spdlog/spdlogConfig.cmake:38 (find_dependency)
  cmake/modules/ChemicalFunFindDeps.cmake:14 (find_package)
  CMakeLists.txt:115 (include)
```

**Comment by gdmiron** [comment]
Try commenting out this part in cmake of chemicalfun find_package(fmt...

**Comment by gdmiron** [comment]
If nothing will work I will make a chemicalfun branch without the logger.

**Comment by defencedog** [comment]
@gdmiron where is this file? I cannot find `fmt` in `CMakeLists.txt` in different locations?

**Comment by gdmiron** [comment]
@defencedog managed to create a clean environment and cmake does not complain about not finding fmt
```
# packages in environment at /home/dmiron/miniconda3/envs/chemicalfun:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
attrs                     21.4.0             pyhd3eb1b0_0  
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                hf3e587d_10    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.07.19           h06a4308_0  
ccache                    3.7.9                hfe4627d_0  
cmake                     3.22.1               h1fce559_0  
eigen                     3.4.0                h4bd325d_0    conda-forge
expat                     2.4.9                h6a678d5_0  
gcc_impl_linux-64         9.4.0               h03d3576_16    conda-forge
gcc_linux-64              9.4.0               h391b98a_10    conda-forge
gxx_impl_linux-64         9.4.0               h03d3576_16    conda-forge
gxx_linux-64              9.4.0               h0316aca_10    conda-forge
importlib-metadata        4.11.3           py37h06a4308_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
iniconfig                 1.1.1              pyhd3eb1b0_0  
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
krb5                      1.19.2               hac12032_0  
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libcurl                   7.84.0               h91b91d3_0  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-devel_linux-64     9.4.0               hd854feb_16    conda-forge
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libnghttp2                1.46.0               hce63b2e_0  
libsanitizer              9.4.0               h79bfe98_16    conda-forge
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-devel_linux-64  9.4.0               hd854feb_16    conda-forge
libstdcxx-ng              11.2.0               h1234567_1  
libuv                     1.40.0               h7b6447c_0  
lz4-c                     1.9.3                h295c915_1  
ncurses                   6.3                  h5eee18b_3  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
nlohmann_json             3.10.5               h295c915_0  
openssl                   1.1.1q               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
pip                       22.2.2           py37h06a4308_0  
pluggy                    1.0.0            py37h06a4308_1  
py                        1.11.0             pyhd3eb1b0_0  
pybind11                  2.9.2            py37h79cecc1_0  
pyparsing                 3.0.9            py37h06a4308_0  
pytest                    7.1.2            py37h06a4308_0  
python                    3.7.13               h12debd9_0  
python_abi                3.7                     2_cp37m    conda-forge
readline                  8.1.2                h7f8727e_1  
rhash                     1.4.1                h3c74f83_1  
setuptools                59.7.0           py37h89c1867_0    conda-forge
spdlog                    1.10.0               h924138e_0    conda-forge
sqlite                    3.39.3               h5082296_0  
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1            py37h06a4308_0  
typing_extensions         4.3.0            py37h06a4308_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.6                h5eee18b_0  
zipp                      3.8.0            py37h06a4308_0  
zlib                      1.2.12               h5eee18b_3  
zstd                      1.5.2                ha4553b6_0  
```
Then using the master branch of chemicalfun:
```
chemicalfun/build$ cmake ..
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/dmiron/miniconda3/envs/chemicalfun/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CCache: using ccache to potentially speed up future build tasks.
-- CondaAware: conda environment recognized!
-- CondaAware: CONDA_PREFIX=/home/dmiron/miniconda3/envs/chemicalfun
-- CondaAware: CONDA_AWARE_PREFIX=CONDA_PREFIX (/home/dmiron/miniconda3/envs/chemicalfun)
-- CondaAware: CMAKE_INSTALL_PREFIX set to CONDA_AWARE_PREFIX
-- CondaAware: appended CONDA_AWARE_PREFIX to CMAKE_PREFIX_PATH
-- CondaAware: appended CONDA_AWARE_PREFIX/include to include directories
-- CondaAware: appended CONDA_AWARE_PREFIX/lib to link directories
-- Found PythonInterp: /home/dmiron/miniconda3/envs/chemicalfun/bin/python (found version "3.7.13") 
-- Found PythonLibs: /home/dmiron/miniconda3/envs/chemicalfun/lib/libpython3.7m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /home/dmiron/miniconda3/envs/chemicalfun/include (found version "2.9.2")
-- Found pybind11 v2.9.2: /home/dmiron/miniconda3/envs/chemicalfun/include;/home/dmiron/miniconda3/envs/chemicalfun/include/python3.7m
-- Found pybind11 v2.9.2: /home/dmiron/miniconda3/envs/chemicalfun/include;/home/dmiron/miniconda3/envs/chemicalfun/include/python3.7m
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found spdlog v1.10.0
-- Configuring done
-- Generating done
```
I wonder why cmake is looking for fmt in your case. The spdlog used in my case is `spdlog   1.10.0`. Now I don't know if it would work to use spdlog with external fmt. For this one could try to compile and install spdlog using `-DSPDLOG_FMT_EXTERNAL_HO=ON` see https://github.com/gabime/spdlog/blob/d011332616464bd0c84817d6255bf5910b7803e9/CMakeLists.txt#L88 . I would still first try having just spdlog with bundled fmt and not external.

**Comment by defencedog** [comment]
@gdmiron  before further trials. Kindly tell of any **test** to know if `spdlog` has bundled `fmt`? For instance any file that it may have that I can check for existence

**Comment by gdmiron** [comment]
The mistery is why it doesn't work with the bundled fmt. In my test this worked, with no fmt. 

I will probably produce a version where one can build chemicalfun and thermofun without spdlog.

**Comment by defencedog** [comment]
@gdmiron 

This seems to be relevant code from `spdlog` system file `/data/data/com.termux/files/usr/lib/cmake/spdlog/spdlogConfig.cmake`
I tried changing ON/OFF switches

```
find_package(Threads REQUIRED)

set(SPDLOG_FMT_EXTERNAL ON)
set(SPDLOG_FMT_EXTERNAL_HO OFF)
set(config_targets_file spdlogConfigTargets.cmake)

if(SPDLOG_FMT_EXTERNAL OR SPDLOG_FMT_EXTERNAL_HO)
    include(CMakeFindDependencyMacro)
    find_dependency(fmt CONFIG)
endif()


include("${CMAKE_CURRENT_LIST_DIR}/${config_targets_file}")
```

**Comment by defencedog** [comment]
Mission accomplished: https://github.com/thermohub/thermofun/issues/39
