### ISSUE TITLE
[Bug]: blender fails to start

### ISSUE THREAD

**Issue by MmyGgithubAaccount** [termux-user-repository/tur#759]
### Problem description

blender fails to start with the following error:
```
Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py", line 1753, in register
    blender_ui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 525, in register
    bpy.types.NODE_MT_category_SH_NEW_OUTPUT.append(add_gltf_settings_to_menu)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_OUTPUT'
Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py", line 44, in register
    gui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 218, in register
    register_message_bus()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 168, in register_message_bus
    bpy.msgbus.subscribe_rna(
TypeError: subscribe_rna: struct FileAssetSelectParams does not contain property asset_library_ref
12589 killed by signal 4
```
[Tombstone](https://github.com/termux-user-repository/tur/files/13793892/tombstone_08.txt) file generated

### What steps will reproduce the bug?

Try to launch blender with the command `termux-x11 :1 -xstartup "dbus-launch --exit-with-session blender"`

### What is the expected behavior?

Blender starts

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~3i79Rcs8CTkyQeThVz4UWA==/com.termux-q-LDJPRV1j1izbbLLctX5w==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=10317
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c105,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c105,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10361
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+27c92fc
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+27c92fc
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.40.1
Android version:
14
Kernel build information:
Linux localhost 5.15.137-Yuni-Beta2-20231218 #99 SMP PREEMPT Mon Dec 18 16:06:38 CST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2210132C
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.boot versionCode:7
```

**Comment by T-Dynamos** [comment]
For info:
It works on my phone (android 13 aarch64)
`termux-info`:
```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=30167
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
# sources.list.d/termux-desktop-xfce.list
deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras
Updatable packages:
All packages up to date
termux-tools version:
1.40.1
Android version:
13
Kernel build information:
Linux localhost 4.9.337~zLOS-a57a7214 #0 SMP PREEMPT Sun Oct 8 10:25:47 CEST 2023 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14
com.termux.styling versionCode:31
```
![image](https://github.com/termux-user-repository/tur/assets/68729523/b48d7b56-ace7-481d-9bd0-c8dedc57196b)
![image](https://github.com/termux-user-repository/tur/assets/68729523/18b35427-3df3-4e6c-b6dc-3155738f04fa)
but frames are pretty low:
```
12-29 19:49:27.482 32315 32329 D gles-renderer: 15 frames in 5.0 seconds = 3.0 FPS
12-29 19:49:29.608 29091 29145 D BufferPoolAccessor2.0: bufferpool2 0x724d778848 : 5(19200 size) total buffers - 4(15360 size) used buffers - 31960/31965 (recycle/alloc) - 33/63921 (fetch/transfer)
12-29 19:49:31.102   959 29153 D BufferPoolAccessor2.0: bufferpool2 0x7895c92538 : 4(96000 size) total buffers - 1(24000 size) used buffers - 32022/32037 (recycle/alloc) - 41/32035 (fetch/transfer)
12-29 19:49:32.482 32315 32329 D gles-renderer: 84 frames in 5.0 seconds = 16.8 FPS
12-29 19:49:34.728 29091 29145 D BufferPoolAccessor2.0: bufferpool2 0x724d778848 : 5(19200 size) total buffers - 4(15360 size) used buffers - 32216/32221 (recycle/alloc) - 33/64433 (fetch/transfer)
12-29 19:49:36.222   959 29153 D BufferPoolAccessor2.0: bufferpool2 0x7895c92538 : 4(96000 size) total buffers - 1(24000 size) used buffers - 32278/32293 (recycle/alloc) - 41/32291 (fetch/transfer)
12-29 19:49:36.841 32315 32329 D gles-renderer: Xlorie: updating cursor
12-29 19:49:36.861 32315 32329 D gles-renderer: Xlorie: updating cursor
12-29 19:49:37.483 32315 32329 D gles-renderer: 21 frames in 5.0 seconds = 4.2 FPS
12-29 19:49:39.848 29091 29145 D BufferPoolAccessor2.0: bufferpool2 0x724d778848 : 5(19200 size) total buffers - 4(15360 size) used buffers - 32472/32477 (recycle/alloc) - 33/64945 (fetch/transfer)
12-29 19:49:41.342   959 29153 D BufferPoolAccessor2.0: bufferpool2 0x7895c92538 : 4(96000 size) total buffers - 1(24000 size) used buffers - 32534/32549 (recycle/alloc) - 41/32547 (fetch/transfer)
12-29 19:49:42.483 32315 32329 D gles-renderer: 1 frames in 5.0 seconds = 0.2 FPS
12-29 19:49:44.993 29091 29145 D BufferPoolAccessor2.0: bufferpool2 0x724d778848 : 5(19200 size) total buffers - 4(15360 size) used buffers - 32727/32732 (recycle/alloc) - 33/65455 (fetch/transfer)
12-29 19:49:46.462   959 29153 D BufferPoolAccessor2.0: bufferpool2 0x7895c92538 : 4(96000 size) total buffers - 1(24000 size) used buffers - 32790/32805 (recycle/alloc) - 41/32803 (fetch/transfer)
12-29 19:49:47.483 32315 32329 D gles-renderer: 1 frames in 5.0 seconds = 0.2 FPS
12-29 19:49:50.110 29091 29145 D BufferPoolAccessor2.0: bufferpool2 0x724d778848 : 5(19200 size) total buffers - 4(15360 size) used buffers - 32985/32990 (recycle/alloc) - 33/65971 (fetch/transfer)
12-29 19:49:51.582   959 29153 D BufferPoolAccessor2.0: bufferpool2 0x7895c92538 : 4(96000 size) total buffers - 1(24000 size) used buffers - 33046/33061 (recycle/alloc) - 41/33059 (fetch/transfer)
12-29 19:49:52.483 32315 32329 D gles-renderer: 1 frames in 5.0 seconds = 0.2 FPS
12-29 19:49:55.230 29091 29145 D BufferPoolAccessor2.0: bufferpool2 0x724d778848 : 5(19200 size) total buffers - 4(15360 size) used buffers - 33241/33246 (recycle/alloc) - 33/66483 (fetch/transfer)
12-29 19:49:56.702   959 29153 D BufferPoolAccessor2.0: bufferpool2 0x7895c92538 : 4(96000 size) total buffers - 1(24000 size) used buffers - 33302/33317 (recycle/alloc) - 42/33315 (fetch/transfer)
12-29 19:49:57.483 32315 32329 D gles-renderer: 2 frames in 5.0 seconds = 0.4 FPS
```

**Comment by MmyGgithubAaccount** [comment]
Ok, so looks like those errors in the console are not related to the crash since they appear for you as well
Crash might be related to android 14 or the soc version
Could someone else on a14 and/or 8gen2 check if it works for them?

**Comment by codrutpopescu** [comment]
a14 and 8gen2 here - it's crashing for me

**Comment by MmyGgithubAaccount** [comment]
@codrutpopescu are you also getting a signal 4 kill?

**Comment by codrutpopescu** [comment]
> @codrutpopescu are you also getting a signal 4 kill?

`Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py", line 1753, in register
    blender_ui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 525, in register
    bpy.types.NODE_MT_category_SH_NEW_OUTPUT.append(add_gltf_settings_to_menu)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_OUTPUT'
Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py", line 44, in register
    gui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 218, in register
    register_message_bus()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 168, in register_message_bus
    bpy.msgbus.subscribe_rna(
TypeError: subscribe_rna: struct FileAssetSelectParams does not contain property asset_library_ref`

**Comment by MmyGgithubAaccount** [comment]
Are you launching through a de like xfce or directly with something like `termux-x11 :1 -xstartup "dbus-launch --exit-with-session blender"`?
If it's the first case, the signal 4 kill will not be printed. Could you try directly launching it and see if it's a signal 4 kill?

Could you also post the tombstone file generated if possible? It's located at `/data/tombstones` (although I'm not sure if it's accessible without root). If that's not possible, a logcat during the crash might also be helpful

**Comment by codrutpopescu** [comment]
> ~ $ termux-x11 :1 -xstartup "dbus-launch --exit-with-session blender"
"The XKEYBOARD keymap compiler (xkbcomp) reports:"
"> "Warning:          Could not resolve keysym XF86CameraAccessEnable
"> "Warning:          Could not resolve keysym XF86CameraAccessDisable
"> "Warning:          Could not resolve keysym XF86CameraAccessToggle
"> "Warning:          Could not resolve keysym XF86NextElement
"> "Warning:          Could not resolve keysym XF86PreviousElement
"> "Warning:          Could not resolve keysym XF86AutopilotEngageToggle
"> "Warning:          Could not resolve keysym XF86MarkWaypoint
"> "Warning:          Could not resolve keysym XF86Sos
"> "Warning:          Could not resolve keysym XF86NavChart
"> "Warning:          Could not resolve keysym XF86FishingChart
"> "Warning:          Could not resolve keysym XF86SingleRangeRadar
"> "Warning:          Could not resolve keysym XF86DualRangeRadar
"> "Warning:          Could not resolve keysym XF86RadarOverlay
"> "Warning:          Could not resolve keysym XF86TraditionalSonar
"> "Warning:          Could not resolve keysym XF86ClearvuSonar
"> "Warning:          Could not resolve keysym XF86SidevuSonar
"> "Warning:          Could not resolve keysym XF86NavInfo
"Errors from xkbcomp are not fatal to the X server"
Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py", line 1753, in register
    blender_ui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 525, in register
    bpy.types.NODE_MT_category_SH_NEW_OUTPUT.append(add_gltf_settings_to_menu)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_OUTPUT'
Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py", line 44, in register
    gui.register()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 218, in register
    register_message_bus()
  File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 168, in register_message_bus
    bpy.msgbus.subscribe_rna(
TypeError: subscribe_rna: struct FileAssetSelectParams does not contain property asset_library_ref
22940 killed by signal 4

**Comment by magbulogtong81** [comment]
> ```
> Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
>     mod.register()
>   File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/__init__.py", line 1753, in register
>     blender_ui.register()
>   File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/io_scene_gltf2/blender/com/gltf2_blender_ui.py", line 525, in register
>     bpy.types.NODE_MT_category_SH_NEW_OUTPUT.append(add_gltf_settings_to_menu)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_OUTPUT'
> Exception in module register(): /data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py
> Traceback (most recent call last):
>   File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
>     mod.register()
>   File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/__init__.py", line 44, in register
>     gui.register()
>   File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 218, in register
>     register_message_bus()
>   File "/data/data/com.termux/files/usr/share/blender/4.0/scripts/modules/pose_library/gui.py", line 168, in register_message_bus
>     bpy.msgbus.subscribe_rna(
> TypeError: subscribe_rna: struct FileAssetSelectParams does not contain property asset_library_ref
> ```
> 

these errors are from the addons that you _can ignore_. i don't know about the signal 4 though have you tried reinstalling?

**Comment by MmyGgithubAaccount** [comment]
This is actually not fixed. I'm still getting signal 4

I think this could be due to 32 vs 64 bit support? 8gen2 only supports 32 bit code on 2/3 cores iirc. Anyone know which ones?
Maybe someone with 8g3 (which doesn't support 32bit at all) can also report what they're getting?

**Comment by lzhiyong** [comment]
blender crashes on Android 14


![Screenshot_2024-08-30-22-11-27-45_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/40cd78af-bd67-4c1a-b302-52e410e907e5)

**Comment by lzhiyong** [comment]
***Android version: 15***
***Python version: 3.12.8***
***Blender version: 3.6.16***
***CPU architecture: aarch64***
![Screenshot_2024-12-11-19-22-28-71_00df01c412509efb9bd6450c382822af](https://github.com/user-attachments/assets/0b8b8eff-c7b7-4d4d-98fc-81d06b1d73ac)

**Comment by lzhiyong** [comment]
cannot locate symbo `_ZN2cv8cvtColorERKNS_11_InputArrayERKNS_12_OutputArrayEii`
```
blender --help

CANNOT LINK EXECUTABLE "blender": cannot locate symbol "_ZN2cv8cvtColorERKNS_11_InputArrayERKNS_12_OutputArrayEii" referenced by "/data/data/com.termux/files/usr/lib/libOpenImageIO.so"
```

**Comment by lzhiyong** [comment]
cannot locate symbol `_ZN2cv8cvtColorERKNS_11_InputArrayERKNS_12_OutputArrayEii`
```
blender --help

CANNOT LINK EXECUTABLE "blender": cannot locate symbol "_ZN2cv8cvtColorERKNS_11_InputArrayERKNS_12_OutputArrayEii" referenced by "/data/data/com.termux/files/usr/lib/libOpenImageIO.so"
```
