### ISSUE TITLE
[Package]: gem ethon

### ISSUE THREAD

**Issue by wakhidrf** [termux-user-repository/tur#831]
### Name

gem ethon

### Source code URL

https://rubygems.org/gems/ethon

### Packaging policy acknowledgement

- [X] I understand [Tur Package Policy](https://github.com/termux-user-repository/tur/wiki/TUR-package-policy.).

### Additional information

Based on bing AI it says
```
It seems you’re encountering an issue with the ffi gem in Ruby on Termux. The error message indicates that the function getdtablesize is not found in libc.so. This function was used by the ethon gem, but it appears to have been removed from the libc of more recent Android distributions.
```

full error log
```
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi/library.rb:216:in `attach_function': Function 'getdtablesize' not found in [libc.so] (FFI::NotFoundError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:17:in `<module:Libc>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:2:in `<top (required)>'            from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'              from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'              from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon.rb:15:in `<top (required)>'                from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'              from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/cms_scanner-0.13.9/lib/cms_scanner.rb:4:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/wpscan-3.8.25/lib/wpscan.rb:8:in `<top (required)>'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/data/data/com.termux/files/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/wpscan-3.8.25/bin/wpscan:4:in `<top (required)>'
        from /data/data/com.termux/files/usr/bin/wpscan:25:in `load'
        from /data/data/com.termux/files/usr/bin/wpscan:25:in `<main>'
```

my device
```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11826
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list                                                  deb https://mirror.mwt.me/termux/main stable main
# tur-repo (sources.list.d/tur.list)                            deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous                                                     Updatable packages:
All packages up to date                                         termux-tools version:
1.40.6                                                          Android version:
14                                                              Kernel build information:
Linux localhost 4.19.191+ #1 SMP PREEMPT Fri Dec 29 19:07:00 CST 2023 aarch64 Android                                           Device manufacturer:
OPPO
Device model:
CPH2387
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

Here's also some reference [sysconf()](https://github.com/wpscanteam/wpscan/issues/1731)
Thank you

**Comment by SunPodder** [comment]
```bash
apt install libffi
```
Then try again

**Comment by SunPodder** [comment]
> nvm, i think it's caused by getdtablesize which isn't supported by the developer, i read somewhere they have tried but fail

I just installed it on my phone :)
```bash
apt install libffi
gem install ethon
```

**Comment by wakhidrf** [comment]
yeah i installed too

https://github.com/typhoeus/ethon/issues/192

```
/data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ffi-1.16.3/lib/ffi/library.rb:216:in `attach_function': Function 'getdtablesize' not found in [libc.so] (FFI::NotFoundError)
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:17:in `<module:Libc>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:7:in `<module:Ethon>'
        from /data/data/com.termux/files/usr/lib/ruby/gems/3.2.0/gems/ethon-0.16.0/lib/ethon/libc.rb:2:in `<top (required)>'
```
