### ISSUE TITLE
[Help wanted] building astrometry.net: cross-compile error

### ISSUE THREAD

**Issue by knyipab** [termux-user-repository/tur#844]
As I'm building astrometry.net package (https://astrometry.net/doc/build.html) with dependency packages https://github.com/termux-user-repository/tur/pull/843 and build.sh below which fails in the make step. Honestly, I do not have much experiencce with termux build system and I found it difficult and really different from on-device building.
```
TERMUX_PKG_HOMEPAGE=https://astrometry.net/
TERMUX_PKG_DESCRIPTION="automatic recognition of astronomical images"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="LICENSE"
TERMUX_PKG_MAINTAINER="@termux-user-repository"
TERMUX_PKG_VERSION="0.94"
TERMUX_PKG_SRCURL=https://github.com/dstndstn/astrometry.net/releases/download/${TERMUX_PKG_VERSION}/astrometry.net-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=38c0d04171ecae42033ce5c9cd0757d8c5fc1418f2004d85e858f29aee383c5f
TERMUX_PKG_DEPENDS="cfitsio, curl, libbz2, libcairo, libjpeg-turbo, libpng, netpbm, python, python-pip, swig, wcslib, zlib"
TERMUX_PKG_PYTHON_COMMON_DEPS="wheel, setuptools"
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_PYTHON_TARGET_DEPS="fitsio"

termux_step_post_configure () {
    cp -r -n "${TERMUX_PKG_SRCDIR}"/* "${TERMUX_PKG_BUILDDIR}/"
}

termux_step_create_debscripts() {
	cat <<-EOF >./postinst
		#!$TERMUX_PREFIX/bin/sh
		echo "Installing dependencies through pip..."
		pip3 install ${TERMUX_PKG_PYTHON_TARGET_DEPS//, / }
	EOF
}
```
I encountered issues in the make step: 
```
make[1]: *** [Makefile:204: config.h] Error 1
make[1]: Leaving directory '/home/vscode/.termux-build/astrometry.net/build/gsl-an'
make: *** [Makefile:105: gsl-an] Error 2
make: *** Waiting for unfinished jobs....
```
and
```
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
make[1]: Nothing to be done for 'config'.
make[1]: Leaving directory '/home/vscode/.termux-build/astrometry.net/build/util'
```
1. the makefile error may be due to incorrect configuration to make subfolder (??). I am not sure and have no idea how to fix. 
2. warning about `setuptools` is not solved with `TERMUX_PKG_PYTHON_COMMON_DEPS` being set 
Really grateful for help to hint me or even supplement this package to TUR. 

Thank you!

**Comment by T-Dynamos** [comment]
@knyipab Post full MakeFile error.

**Comment by knyipab** [comment]
Sorry I forgot to post the build log. Attached below. 
[astrometry.net.log](https://github.com/termux-user-repository/tur/files/14380313/astrometry.net.log)

**Comment by T-Dynamos** [comment]
```
./os-features-test-netpbm >> os-features.log && \       echo "#define HAVE_NETPBM 1") \                      || echo "#define HAVE_NETPBM 0") >> ../include/astrometry/os-features-config.h.tmp     
/bin/sh: 3: ./os-features-test-netpbm: Exec format error
--------------- End of expected error messages ---------
```

It tried to run an another architecture executable on another architecture. You may need to build this using `tur-on-device`

**Comment by knyipab** [comment]
I tried `tur-on-device` but I don't even get through the python installation of `TERMUX_PKG_PYTHON_TARGET_DEPS="fitsio"`. Grateful for help. Thanks. 

I managed to install `fitsio`in a **clean emulated x86_64 device** with commands below: 
```
pkg update
pkg install python python-numpy # dependencies
pkg install ninja patchelf # to get through install numpy dependencies error
pkg install binutils # to get through configure command ar not found error
LDFLAGS+=" -Wl,--no-as-needed,-lpython3.11,--as-needed" pip install fitsio
# LDFLAGS set to get through the numpy import error
```

My `tur-on-devce` build.sh is written as below to try to replicate commands above: 
```sh
TERMUX_PKG_HOMEPAGE=https://astrometry.net/
TERMUX_PKG_DESCRIPTION="automatic recognition of astronomical images"
TERMUX_PKG_LICENSE="custom"
TERMUX_PKG_LICENSE_FILE="LICENSE"
TERMUX_PKG_MAINTAINER="@termux-user-repository"
TERMUX_PKG_VERSION="0.94"
TERMUX_PKG_SRCURL=https://github.com/dstndstn/astrometry.net/releases/download/${TERMUX_PKG_VERSION}/astrometry.net-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=38c0d04171ecae42033ce5c9cd0757d8c5fc1418f2004d85e858f29aee383c5f
TERMUX_PKG_DEPENDS="cfitsio, curl, libbz2, libcairo, libjpeg-turbo, libpng, netpbm, python, python-numpy, swig, wcslib, zlib"
TERMUX_PKG_BUILD_DEPENDS="ninja, patchelf, binutils"
TERMUX_PKG_PYTHON_COMMON_DEPS="wheel"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_AUTO_UPDATE=true	
TERMUX_PKG_PYTHON_TARGET_DEPS="fitsio"

termux_step_pre_configure() {
	LDFLAGS+=" -Wl,--no-as-needed,-lpython${TERMUX_PYTHON_VERSION},--as-needed"
}

termux_step_create_debscripts() {
	cat <<-EOF >./postinst
		#!$TERMUX_PREFIX/bin/sh
		echo "Installing dependencies through pip..."
		pip3 install ${TERMUX_PKG_PYTHON_TARGET_DEPS//, / }
	EOF
}
```
It comes with configure error below ([full log](https://github.com/knyipab/tur/actions/runs/8028262374/job/21933246027)): 
```
checking build system type... x86_64-pc-linux-gnu
      checking host system type... x86_64-pc-linux-gnu
      checking target system type... x86_64-pc-linux-gnu
      checking for gcc... x86_64-linux-android-clang
      checking whether the C compiler works... no
      configure: error: in `/data/data/com.termux/files/usr/tmp/pip-install-27c3mh9d/fitsio_eb7a31d84f114e8da271bb5cc32a784d/build/temp.linux-x86_64-cpython-311/cfitsio-4.2.0':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-install-27c3mh9d/fitsio_eb7a31d84f114e8da271bb5cc32a784d/setup.py", line 319, in <module>
          setup(
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-install-27c3mh9d/fitsio_eb7a31d84f114e8da271bb5cc32a784d/setup.py", line 106, in run
          build_ext.run(self)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/data/data/com.termux/files/home/.termux-build/astrometry.net/tmp/venv-dir/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/data/data/com.termux/files/usr/tmp/pip-install-27c3mh9d/fitsio_eb7a31d84f114e8da271bb5cc32a784d/setup.py", line 130, in build_extensions
          self.configure_cfitsio(
        File "/data/data/com.termux/files/usr/tmp/pip-install-27c3mh9d/fitsio_eb7a31d84f114e8da271bb5cc32a784d/setup.py", line 272, in configure_cfitsio
          raise ValueError(
      ValueError: could not configure cfitsio 4.2.0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fitsio
  Running setup.py clean for fitsio
Failed to build fitsio
```

**Comment by T-Dynamos** [comment]
> TERMUX_PKG_PYTHON_TARGET_DEPS="fitsio"

I think this is not required, According to https://astrometrynet.readthedocs.io/en/latest/build.html only `cfitsio` is required.

**Comment by knyipab** [comment]
Still, `pyfits` is needed (if `fitsio` is not there). According to https://astrometry.net/doc/readme.html, either one of `fitsio`, `astropy` or `pyfits` is required. 

* `fitsio` seems to be the easiest one to compile
* `astropy` did compile few years ago on my device, but the current version runs into compilation issues (`pip install`)
* `pyfits` depends on its own python distutils `stsci.distutils` which does not compile with `pip install`

This `astrometry.net` package is promising, once we solve the building issue using `tur-on-device`. The reason I say this is that I managed to get it work in my emulateed device with complete steps below and yielded some actual result:

![Screenshot from 2024-02-24 14-54-37](https://github.com/termux-user-repository/tur/assets/46513942/3ceea522-8be7-4e2d-b950-0cc0aa6b75cd)

## install `fitsio`
```
pkg update
pkg install python python-numpy # dependencies
pkg install ninja patchelf # to get through install numpy dependencies error
pkg install binutils # to get through configure command ar not found error
LDFLAGS+=" -Wl,--no-as-needed,-lpython3.11,--as-needed" pip install fitsio
# LDFLAGS set to get through the numpy import error
```
## install `astrometry.net`
```
git clone https://github.com/dstndstn/astrometry.net
git checkout 0.94
pkg install tur-repo
pkg install cfitsio curl file libbz2 libcairo libjpeg-turbo libpng netpbm swig wcslib zlib
make
make py CAIRO_INC=-I"$PREFIX"/include/cairo
make extra CAIRO_INC=-I"$PREFIX"/include/cairo
make install INSTALL_DIR="$PREFIX" CAIRO_INC=-I"$PREFIX"/include/cairo
```
## fits database needed to get it work
```
pkg install wget
wget -P $PREFIX/data http://data.astrometry.net/4100/index-4115.fits http://data.astrometry.net/4100/index-4116.fits http://data.astrometry.net/4100/index-4117.fits http://data.astrometry.net/4100/index-4118.fits http://data.astrometry.net/4100/index-4119.fits
```
I will perhaps pacakge these file into another package. 
## test with a [Google Pixel Astrophoto from Google Blog](https://blog.research.google/2019/11/astrophotography-with-night-sight-on.html)
```
wget https://1.bp.blogspot.com/-RET3jzHjUdI/Xd2Z3zO_bVI/AAAAAAAAE-g/m9gTuElmcasdxzCVfI7QrKs6wmFpwW6zQCLcBGAsYHQ/s1600/image10.jpg
image_file=image10.jpg
solve-field -D output --no-plots -m "$PREFIX/tmp" --objs 1000 "$image_file"
jpegtopnm ${image_file} | plot-constellations -w output/${image_file%%.jpg}.wcs -o output-constellations.png -i - -B -b 5 -G 600 -g 0.8,0.8,0.8
plotann.py output/${image_file%%.jpg}.wcs ${image_file} output-ann.png --grid-size=5 --grid-label=15 --grid-color=0.8:0.8:0.8 --lw=10
```

**Comment by knyipab** [comment]
FYI, I gave up building the cfitsio inside that the fitsio project in TUR which is so difficult, and ended up packaging `python-fitsio` by setting `FITSIO_USE_SYSTEM_FITSIO=1` in #847. 

Will retry building astrometry.net after it is merged.

**Comment by knyipab** [comment]
Completed with #850.
Lesson learnt is that subfolder calling configure without passing cross-compile argument `--host`.

**Comment by Saikatsaha1996** [comment]
## [Help wanted]
@T-Dynamos 
According to this post.. i also want help..
I want to cross-compile XYZ.package in Termux.. 
My host system 64 bit.. i want to compile with 32bit..
For this package required ton of 32bit dependency.. but I am on host 64bit..
So for that case any way to cross compile 32bit  on host 64 bit ? I mean how can I manage 32bit dependency for cross compile..

Help appreciated.. 👍
Thank you
